// EconSim: the market Ingvar will run, played off-game before anyone plays it.
//
//   dotnet run --project tests\EconSim\EconSim.csproj -c Release                     # to stdout
//   dotnet run --project tests\EconSim\EconSim.csproj -c Release -- --out docs\ECONOMY-SIM.md
//
// Deterministic: one seed, no wall clock, no System.Random, no dictionary order in the
// output. Two runs produce the same bytes. Exit code 1 if an assertion in scenario 7 or 8
// failed, so the script that regenerates the report is also a test.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using RavenIron.ValkyriesCargo.Core;

namespace ValkyriesCargo.EconSim
{
    public static class Program
    {
        public const int MasterSeed = 20260906;

        public static int Main(string[] args)
        {
            string outPath = null;
            long seed = MasterSeed;
            for (int i = 0; i < args.Length; i++)
            {
                if (args[i] == "--out" && i + 1 < args.Length) { outPath = args[++i]; continue; }
                if (args[i] == "--seed" && i + 1 < args.Length)
                {
                    long s;
                    if (!long.TryParse(args[i + 1], NumberStyles.Integer, CultureInfo.InvariantCulture, out s))
                    {
                        Console.Error.WriteLine("--seed wants a whole number");
                        return 2;
                    }
                    seed = s; i++; continue;
                }
                Console.Error.WriteLine("usage: EconSim [--out <file>] [--seed <n>]");
                return 2;
            }

            var md = new Md();
            Header(md, seed);
            Scenarios.One(md, seed);
            Scenarios.Two(md, seed);
            Scenarios.Three(md, seed);
            Scenarios.Four(md, seed);
            Scenarios.Five(md, seed);
            Scenarios.Six(md, seed);
            Checks.Seven(md, seed);
            Checks.Eight(md, seed);
            Scenarios.Nine(md, seed);
            Verdict(md, seed);

            string text = md.Render();
            if (outPath != null)
            {
                string dir = Path.GetDirectoryName(Path.GetFullPath(outPath));
                if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
                File.WriteAllText(outPath, text, new UTF8Encoding(false));
                Console.WriteLine("wrote " + outPath + ", " + Sim.N(text.Length) + " characters; checks " +
                                  (Checks.AllPassed ? "PASSED" : "FAILED"));
            }
            else
            {
                Console.Out.Write(text);
            }
            return Checks.AllPassed ? 0 : 1;
        }

        // =====================================================================================

        private static void Header(Md md, long seed)
        {
            md.Line("# Ingvar's economy, played off-game");
            md.Blank();
            md.Line("*Generated by `tests/EconSim` from the shipping `ValkyriesCargo/Core` sources. Do not edit by hand.*");
            md.Blank();
            md.Line("Seed **" + Sim.N(seed) + "**. Regenerate:");
            md.Blank();
            md.Line("```powershell");
            md.Line(".\\tools\\run-econsim.ps1");
            md.Line("# or: dotnet run --project tests\\EconSim\\EconSim.csproj -c Release -- --out docs\\ECONOMY-SIM.md");
            md.Line("```");
            md.Blank();
            md.Line("The economy is blind until players trade (DESIGN section 12), and the first real visit has not happened yet. This");
            md.Line("report is that visit, simulated: `Market.StartVisit`, `Market.Settle` and `Market.Relax` — the same file the server");
            md.Line("runs, compiled into a console harness the way `tests/CoreTests` does it — driven by players with coins, bags and");
            md.Line("appetites. Every number below came out of the code, not out of a model of the code. Nothing here changes a default:");
            md.Line("the last section proposes, the owners decide.");

            var rules = MarketRules.Default;
            Catalogue cat = Sim.DefaultCatalogue();
            md.Blank();
            md.Table(new[] { "the numbers it ran on", "value", "where from" }, new List<string[]>
            {
                new[] { "catalogue", Sim.N(cat.Count) + " entries (" + Sim.N(cat.CountOf(EntryKind.Ware)) + " Wares, " + Sim.N(cat.CountOf(EntryKind.Want)) + " Wants)", "`Catalogue.DefaultLine`, parsed by the shipping parser" },
                new[] { "`PriceElasticity`", Sim.F(rules.Elasticity, 2), "`ModConfig` default" },
                new[] { "`MinPriceMultiplier` / `MaxPriceMultiplier`", Sim.F(rules.MinMultiplier, 1) + " / " + Sim.F(rules.MaxMultiplier, 1), "`ModConfig` defaults" },
                new[] { "`SpreadBuy`", Sim.F(rules.Spread, 1), "`ModConfig` default" },
                new[] { "`StockHalfLifeGameDays`", Sim.F(rules.HalfLifeGameDays, 1), "`ModConfig` default" },
                new[] { "`PurseCoins` / `PurseCarryPercent` / cap", Sim.N(rules.PurseCoins) + " / " + Sim.N(rules.PurseCarryPercent) + "% / " + Sim.N(rules.PurseCapMultiple) + "x", "`ModConfig` defaults" },
                new[] { "a game day", Sim.F(rules.SecondsPerGameDay, 0) + " s", "`EnvMan.m_dayLengthSec`, verified on StormTest 2026-09-06" },
            });
        }

        // =====================================================================================

        private static void Verdict(Md md, long seed)
        {
            md.H(2, "Verdict — what to keep and what to change");

            md.Line("Proposals only. No shipping default was changed to produce this report.");

            md.H(3, "What is right");

            // The four vanilla anchors, checked against CATALOGUE section 1.
            Market m = Sim.NewMarket(0);
            var anchors = new List<string[]>();
            string[][] anchorData = { new[] { "Amber", "5" }, new[] { "AmberPearl", "10" }, new[] { "Ruby", "20" }, new[] { "SilverNecklace", "30" } };
            bool anchorsHold = true;
            foreach (string[] a in anchorData)
            {
                MarketItem it = m.Find(a[0]);
                int pays = Market.PaysFor(it.Entry.BasePrice, it.Entry.TargetStock, it.Entry.TargetStock, m.Rules);
                bool ok = Sim.N(pays) == a[1];
                if (!ok) anchorsHold = false;
                anchors.Add(new[] { a[0], Sim.N(it.Entry.BasePrice), a[1], Sim.N(pays), ok ? "holds" : "**off**" });
            }
            md.Line("**`SpreadBuy` 0.7 and the four anchor bases.** CATALOGUE section 1 sets Amber, Amber Pearl, Ruby and the Silver");
            md.Line("Necklace so that Ingvar pays Haldor's flat rate at target stock. He does, to the coin:");
            md.Blank();
            md.Table(new[] { "row", "base", "Haldor pays", "Ingvar pays at target", "" }, anchors);
            md.Line(anchorsHold
                ? "That is the whole argument for walking to the merchant, and it survives the rounding rule. Keep 0.7."
                : "**An anchor has drifted — check the base prices against CATALOGUE section 1.**");
            md.Blank();
            md.Line("**`PriceElasticity` 0.35.** A full Amber shelf walks 7 -> 21 coins as it empties (scenario 1) and scrap iron walks");
            md.Line(Sim.Fact("s2.scraprange") + " as it fills (scenario 2). Big enough to notice in a session, small enough that two or three deals do not");
            md.Line("wreck a row. Keep it.");
            md.Blank();
            md.Line("**`StockHalfLifeGameDays` 1.** Every row damaged in scenarios 1 and 2 is back inside 5% of target within " +
                    Sim.Fact("s6.days") + " game days");
            md.Line("(scenario 6), and a shelf emptied every single day settles at half target rather than collapsing. Keep it.");
            md.Blank();
            md.Line("**The pure core's bounds.** " + Sim.Fact("s8.accepted") + " settled deals out of ten thousand random ones, and not a single throw, negative");
            md.Line("stock, over-max shelf, negative purse, sub-1 price or repeated delivery id (scenario 8). The refusal order is the one");
            md.Line("the contract describes (scenario 7). This part is done.");

            md.H(3, "What looks off");

            if (Sim.Fact("s9.best") == "none")
            {
                md.Line("**1. RESOLVED 2026-09-07 — the round trip.** `MaxPriceMultiplier` 3.0 x `SpreadBuy` 0.7 = 2.1, and 2.1 > 1, so");
                md.Line("Ingvar used to buy his own Wares back for more than he sold them: 17 of the 18 were profitable to buy out and sell");
                md.Line("straight back, a player could walk off with his whole purse on the first visit, and the shelves ended exactly where");
                md.Line("they started so nothing in the saved state showed it.");
                md.Blank();
                md.Line("Closed by the **Fair Market Act** (`Server.FairMarketAct`, synced and locked, default on): a Ware's buy-back");
                md.Line("multiplier is clamped at 1.0, so he never pays more than `base x SpreadBuy` for something he himself sells. What he");
                md.Line("CHARGES still rises to the full 3.0x and Wants are untouched, so the scarcity signal survives everywhere it was");
                md.Line("meant to be. The owners chose this over the config-only fix (`MaxPriceMultiplier` 3.0 -> 1.4, the 1/0.7 = 1.43");
                md.Line("break-even) precisely because that one would have thrown the signal away. Reasoning: `docs/DECISIONS-WUBARRK.md` 2.");
                md.Blank();
                md.Line("Scenario 9 above is the standing proof: all 18 Wares now LOSE the player coins. Turn the knob off and the pump");
                md.Line("table comes back — that is the regression test, and it is why the knob was kept rather than the clause hardcoded.");
            }
            else
            {
                md.Line("**1. `MaxPriceMultiplier` 3.0 x `SpreadBuy` 0.7 = 2.1, and 2.1 > 1: he buys his own wares back for more than he sold");
                md.Line("them.** Scenario 9. Buy a shelf out at the full-shelf price, sell it straight back at the empty-shelf price, and the coins");
                md.Line("come out of his purse — " + Sim.Fact("s9.pervisit") + " coins on the first visit, on " + Sim.Fact("s9.best") + ", with the shelf left exactly where it started so nothing in");
                md.Line("the saved state shows it happened. This is the one finding I would not ship without a decision on.");
                md.Blank();
                md.Line("*The config-only fix is `MaxPriceMultiplier` 3.0 -> 1.4* (`1 / SpreadBuy` = 1.43 is the break-even), which also throws away");
                md.Line("most of the scarcity signal the mod is for. *The cheap code fix is one clause in `Market.Pays`*: when the offered row is a");
                md.Line("Ware, price the buy-back at `min(multiplier, 1.0)`, so he never pays more than `base x spread` for something he sells. A");
                md.Line("player who empties a shelf then repents still gets his coins back at the ordinary rate, and the pump dies. Either way it");
                md.Line("is a decision for DESIGN section 8, next to 'a bulk deal beats a drip-feed', which is where it comes from.");
            }
            md.Blank();
            md.Line("**2. `MinPriceMultiplier` 0.4 is unreachable and always will be.** Every one of the 72 rows has `Max = 3 x Target`, so the");
            md.Line("lowest multiplier any shelf can reach by trading is `(1/3)^0.35 = " + Sim.Fact("floor.min") + "`; the floor would need `Max > 13.7 x Target`.");
            md.Line("Nothing is broken — but the knob reads like a promise the catalogue cannot keep. *Change the documentation, not the");
            md.Line("number*: `MinPriceMultiplier` is a guard for an owner's edited catalogue, not a price a player will ever see. If a real");
            md.Line("flooded floor is wanted, the number to change is `MaxStock` in the catalogue (3x -> 5x on the high-volume Wants), not the");
            md.Line("multiplier.");
            md.Blank();
            md.Line("**3. " + Sim.Fact("floor.flatcount") + " rows pay the same single coin whatever you do to them.** `PaysFor`'s `max(1, ...)` swallows the whole curve for");
            md.Line("every row with a base of 1 or 2: " + Sim.Fact("floor.flat") + ".");
            md.Line("Wood, stone, resin, coal and flint *should* be near-worthless — that is the joke. But **RoundLog, FineWood, Feathers and");
            md.Line("LeatherScraps sit at base 2 and pay exactly what wood pays**, though core wood is 15 recipes, fine wood is 31 and leather");
            md.Line("scraps 32 (CATALOGUE section 3). *Proposal: raise `RoundLog`, `FineWood`, `Feathers` and `LeatherScraps` from base 2 to 3*, which");
            md.Line("pays 2 at target and 1 when flooded — a visible signal, a distinction from firewood, and a stack of fifty worth 100 coins");
            md.Line("rather than 50.");
            md.Blank();
            md.Line("**4. `PurseCoins` 800 is thin for the trade the mod exists for, and `PurseCarryPercent` never fires on the servers that");
            md.Line("need it.** Non-teleportable ore is the reason he lands at the base with the smelter (CATALOGUE section 1), and " + Sim.Fact("s3.exhaust") + ".");
            md.Line("A dozen flametal ore is the whole purse. Then the carry: `Takings` is `Purse - purseAtVisitStart` floored at zero, so it is");
            md.Line("the visit's NET, and any visit in which players sell him as much as they buy carries nothing forward (scenario 3: takings");
            md.Line(Sim.Fact("s3.takingsafterselling") + " after a visit of pure selling). Over twenty visits the cap engaged " + Sim.Fact("s3.caphits") + " times for a shopping server and " + Sim.Fact("s3.capboth") + " times for a");
            md.Line("server that also sells to him. A supplying server — the one the catalogue was written for — sees a flat 800 for ever.");
            md.Blank();
            md.Line("*Proposal, two numbers: `PurseCoins` 800 -> 1500*, which is two stacks of silver ore or a good afternoon in the Ashlands and");
            md.Line("leaves the 3x cap meaningful; *and change what the carry is measured on* — half of the coins that came IN (gross), not half");
            md.Line("of the net, so a busy visit refills him whichever direction the goods went. That second one is a change to `Market.Takings`");
            md.Line("and belongs in a decision line, not a config edit.");
            md.Blank();
            int coreAt2 = Market.PriceFor(300, 2, 1, m.Rules);
            int coreAt3 = Market.PriceFor(300, 3, 1, m.Rules);
            md.Line("**5. `BlackCore` has a target of 2 and therefore almost no price at all.** Its multiplier cannot pass " +
                    Sim.F(Market.MultiplierFor(2, 1, m.Rules), 2) + " even with the shelf");
            md.Line("empty, so the rarest thing he carries is the one whose price barely moves. It is also the one Ware the round trip");
            md.Line("cannot exploit (item 1), which is an accident rather than a design. *Either leave it — the scarcity is the stock, not");
            md.Line("the price — or raise it to `BlackCore:300:3:9`*, which makes the last one cost " + Sim.N(coreAt3) + " instead of " + Sim.N(coreAt2) + " and puts a third on the shelf.");

            md.H(3, "Not a number, but worth knowing");

            md.Line("- **The server takes the player's word for his coins.** `VisitDirector.Settle` passes `deal.CoinsOffered` — a client-supplied");
            md.Line("  field — as `playerCoins` (VisitDirector.cs 247), and `Settle` never checks that the player actually carries the goods on");
            md.Line("  the offered lines. `coins_short` is therefore advisory, and a modified client can sell him what it does not have. The");
            md.Line("  pure core cannot fix this: the check belongs on the server side of the wire, against the peer's inventory.");
            md.Line("- **A Want asked for as a Ware answers `unknown_item`** (Market.cs 272), so the terminal cannot say 'he only buys those'.");
            md.Line("- **`Relax` is path-dependent.** Rounding away from zero moves at least one unit per call, so N daily calls close a gap");
            md.Line("  faster than one call N days later (scenario 6's two columns). The server calls it once a visit, so this is a difference");
            md.Line("  between a busy server and a quiet one, not a bug — but a shelf recovers faster on the server people play on.");
            md.Line("- **A market that has never started a visit will settle a deal numbered 0** (`VisitId` starts at 0). Unreachable through");
            md.Line("  `VisitDirector`, which refuses `visit_over` first.");
        }
    }
}
